### ISSUE TITLE
poliastro API change

### ISSUE THREAD

**Issue by wumpus** [FedericoStra/tletools#5]
`from tletools import TLE` is currently crashing trying to find `poliastro.core.angles.M_to_nu`

Staring more closely at the problem, seems that M_to_nu might have been lost in a refactor, I will ask the poliastro guy:

https://github.com/poliastro/poliastro/issues/937

**Comment by astrojuanlu** [comment]
Hi! I left [a comment](https://github.com/poliastro/poliastro/issues/937#issuecomment-621095587) in poliastro explaining why I dropped these functions. If @FedericoStra you are still maintaining this package, perhaps you want to replace `M_to_nu(M, ecc)` by `E_to_nu(M_to_E(M, ecc), ecc)`? TLEs only contain elliptic orbits anyway, and the eccentricities are contained.

**Comment by codinghipster** [comment]
PR out for this, @FedericoStra any chance you can take a look at it?

**Comment by FedericoStra** [comment]
Sorry for the delay and thank to everybody for the interest. I'm reviewing the proposed solution and will update as soon as possible.

**Comment by FedericoStra** [comment]
This issue should be resolved now. I merged #7 and added the fix also to the class `TLEu`, which was missing.

**Comment by wumpus** [comment]
Thank you!
